mySite/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

mySite/main/routes.py
from flask import render_template, request, Blueprint, redirect
from mySite.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/index")
def index():
    return render_template('index.html',title='Intro')


@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(status=1).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts, title="Blog")
#    return render_template('under.html')


@main.route("/approve")
def approve_post():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(status=0).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('approve.html', posts=posts)



@main.route("/about")
def about():
    return render_template('about.html', title='About')
#    return render_template('under.html')

@main.route("/manifesto")
def manifesto():
    # with open('static/manifesto.pdf', 'rb') as static_file:
    #     return send_file(static_file, attachment_filename='manifesto.pdf')
    return redirect("static/manifesto.pdf")

mySite/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from mySite import db
from mySite.models import Post
from mySite.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created! Your post will be visible after approval.', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    cond_1=(post.author != current_user)
    cond_2=(current_user.privelege==0)
    if (cond_1 and cond_2):
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/approve", methods=['POST'])
@login_required
def approve_post(post_id):
    post = Post.query.get_or_404(post_id)
    if (current_user.privelege==0):
        abort(403)
    post.status=1
    db.session.commit()
    flash('The post has been approved!', 'success')
    return redirect(url_for('main.approve_post'))

mySite/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify, abort, current_app, send_from_directory
from flask_login import login_user, current_user, logout_user, login_required
from mySite import db, bcrypt
from mySite.models import User, Post, Body_type, Body_name, District_name
from mySite.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from mySite.users.utils import save_picture, send_reset_email
import xlsxwriter 
from datetime import datetime
import os

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    form.district.choices=[(district.id,district.name) for district in District_name.query.all()]
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        
        
        t_name=Body_type.query.filter_by(id=form.lsg_type.data).first().name
        d_name=District_name.query.filter_by(id=form.district.data).first().name
        l_name=Body_name.query.filter_by(id=form.lsg_name.data).first().name

        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password,localBodyType=t_name,
                    district=d_name,localBodyName=l_name,
                    phone=form.phone.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/register/districtSelect")
def returningDistrict():
    typeList=Body_type.query.all()
    typeArray=[]
    for a in typeList:
        typeObj={}
        typeObj['name']=a.name
        typeObj['id']=a.id
        typeArray.append(typeObj)
    return jsonify({'listOfTypes':typeArray})

@users.route("/register/nameSelect/<getString>")
def returningType(getString):
    getDistrict,getType=getString.split()
    t_id=int(getType)
    d_id=int(getDistrict)
    nameList = Body_name.query.filter_by(type_id=t_id,district_id=d_id).all()
    nameArray = []
    for lsgName in nameList:
        nameObj = {}
        nameObj['name'] = lsgName.name
        nameObj['id']= lsgName.id
        nameArray.append(nameObj)
    return jsonify({'lsgnames' : nameArray})



@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        
        
        current_user.localBodyType = Body_type.query.filter_by(id=form.lsg_type.data).first().name
        current_user.district = District_name.query.filter_by(id=form.district.data).first().name
        current_user.localBodyName = Body_name.query.filter_by(id=form.lsg_name.data).first().name
        
        current_user.phone = form.phone.data
        
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.phone.data = current_user.phone
        form.district.choices=[(District_name.query.filter_by(name=current_user.district).first().id,current_user.district)]
        form.lsg_name.choices=[(Body_name.query.filter_by(name=current_user.localBodyName).first().id,current_user.localBodyName)]
        form.lsg_type.choices=[(Body_type.query.filter_by(name=current_user.localBodyType).first().id,current_user.localBodyType)]
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/register/districtClick")
def returningClick():
    districtList=District_name.query.all()
    distArray=[]
    for a in districtList:
        distObj={}
        distObj['name']=a.name
        distObj['id']=a.id
        distArray.append(distObj)
    return jsonify({'listOfdist':distArray})



@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user,status=1)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/user/<int:user_id>/delete", methods=['POST'])
@login_required
def delete_user(user_id):
    if (current_user.privelege==0):
        abort(403)
    user = User.query.get_or_404(user_id)
    for post in user.posts:
        db.session.delete(post)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('main.home'))


@users.route("/user/data")
@login_required
def data():
    if (current_user.privelege==0):
        abort(403)
    user_list = User.query.all()
    name = os.path.join(current_app.root_path, 'static/data_files/myData.xlsx')
    directory= os.path.join(current_app.root_path, 'static/data_files')
    path='myData.xlsx'
    workbook = xlsxwriter.Workbook(name) 
    worksheet = workbook.add_worksheet() 
    date=datetime.utcnow().strftime('%d-%m-%Y')
    worksheet.write(0, 0,date )
    row = 1
    column = 0   
    
    heading=['Id', 'Username', 'Email', 'Phone', 'District', 'LocalBodyType', 'LocalBodyName']
    for head in heading :
        worksheet.write(row, column, head)
        column += 1
    row=2
    for item in user_list:
        column=0
        line=[item.id, item.username, item.email, item.phone, item.district, item.localBodyType, item.localBodyName]
        for block in line :
            worksheet.write(row, column, block)
            column += 1
        row+=1
    workbook.close()
    return send_from_directory(directory, path, as_attachment=True)





@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

mySite/templates/approve.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

mySite/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">   
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='font-awesome.min.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    {% if title %}
        <title>NKPP - {{ title }}</title>
    {% else %}
        <title>NKPP</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top">
        <div class="container">
          <!--<img class="rounded-circle article-img" src="{{ url_for('static', filename='logo.png') }}">-->
          <a class="navbar-brand mr-4 nav-link" href="/" style="font-family:verdana;"><b>NAVA KERALA PEOPLE'S PARTY</b></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.index') }}" >Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}" >Blog</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}" >About</a>
              <a class="nav-item nav-link" href="{{ url_for('main.manifesto') }}" target="_blank" >Manifesto</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              
             
              {% if current_user.privelege==1 %}
                <a class="nav-item nav-link" href="{{ url_for('main.approve_post') }}">Approve Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.data') }}">Data</a>
              {% endif %}
              
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Become a Member</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    {%if title!='About' and title!='Intro' %}
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            
            <p class='text-muted'>
              <ul class="list-group">
              <li class="list-group-item list-group-item-light"><img src="{{ url_for('static', filename='flag1.png') }}" width="100%" height="100%"></li>
                <li class="list-group-item list-group-item-light">Democratic | Socialist | Secular</li>
                <li class="list-group-item list-group-item-light">കേരള ജനത ഏറ്റവും കൂടുതൽ ചർച്ച ചെയ്യുന്ന വിഷയങ്ങൾ.</li>
                <li class="list-group-item list-group-item-light">അഴിമതി. എല്ലാ രംഗങ്ങളിലും അഴിമതി നിറഞ്ഞുനിൽക്കുന്നു. അഴിമതി രഹിത ഭരണം എങ്ങനെ പ്രാവർത്തികമാക്കാൻ കഴിയും?</li>
                <li class="list-group-item list-group-item-light">കെടുകാര്യസ്ഥത. മന്ത്രിസഭയും ഗവണ്മെന്റ് ഓഫീസികളും കെടുകാര്യസ്ഥതയുടെ കൂത്തമ്പലമാണ്. എങ്ങനെ കാര്യക്ഷമമായി കേരളം ഭരിക്കാം?</li>
                <li class="list-group-item list-group-item-light">സർക്കാരിന്റെ കടബാധ്യത. ധനകാര്യ നടത്തിപ്പിൽ ഒരു പ്രാവീണ്യവും ഇല്ലാത്തവരാണ് ഇതുവരെ ധനകാര്യ മന്ത്രാലയം കൈകാര്യം ചെയ്തതെന്ന് 64 വര്ഷം കൊണ്ട് 3 ലക്ഷം കോടി കടബാധ്യത ഉണ്ടാക്കിയതിൽ നിന്ന് നമുക്ക് മനസിലാക്കാം. എങ്ങനെ ഇതിൽ നിന്ന് കരകയറാൻ പറ്റും?</li>
                <li class="list-group-item list-group-item-light">നഷ്ട്ട കച്ചവടമായി കൃഷി. കൃഷി എങ്ങനെ ലാഭകരമാക്കും?</li>
                <li class="list-group-item list-group-item-light">വ്യവസായത്തിൽ നിന്നുള്ള സംസ്ഥാന വരുമാനം തുലോം തുച്ഛം. സമരങ്ങൾ പ്രധാന കാരണമെന്ന് എല്ലാവർക്കുമറിയാം. എങ്ങനെ വ്യവസായം മെച്ചപ്പെടുത്താം?</li>
                
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
    {%else%}
    <main role="main" class="container">
     {% block content2 %}{% endblock %}
    </main>
    {%endif%}


<!-- -->

		<footer class="footer-distributed">

			<div class="footer-left">
             <img src="{{ url_for('static', filename='flag.png') }}">
				<h3>NKP<span> party</span></h3>

				<p class="footer-links">
					<a href="#">Democratic</a>
					|
					<a href="#">Socialist</a>
					|
					<a href="#">Secular</a>
				</p>

				<p class="footer-company-name">© 2020 Nava Kerala People's Party.</p>
				
					
				
			</div>

			<div class="footer-center">
				<div>
					<i class="fa fa-map-marker"></i>
					  <p><span>10 / 1631 - Athani,
						 Kusumagiri.P.O, Kakkanad</span>
						Ernakulam, Kerala - 682 030</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+91 755 884 4814</p>
				</div>
				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:nkpparty@gmail.com">nkpparty@gmail.com</a></p>
				</div>
			</div>
			<div class="footer-right">
				<p class="footer-company-about">
					<span>Nava Kerala People's Party</span>
					A regional political party based in Kerala.The goal of this collaborative work is to develop and envisage a developed state.</p>
				<div class="footer-icons">
					<a href="https://www.facebook.com/nkpparty.org" target="_blank"><i class="fa fa-facebook"></i></a>
					<a href="https://www.twitter.com/NkpParty" target="_blank"><i class="fa fa-twitter" ></i></a>
					<a href="https://youtube.com/channel/UC4qYyIHNwTlm7je84saxknw" target="_blank"><i class="fa fa-youtube"></i></a>
				</div>
			</div>
		    <div>
        		<a href="https://www.linkedin.com/in/joel-jose-527b80102" target="_blank" >Designed By Joel Jose</a>  
			</div> 
		</footer>


 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mySite/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            {% if current_user.privelege==1 %}
            {% if post.status==0%}
            <button type="button" class="btn btn-secondary btn-sm mt-1 mb-1" data-toggle="modal" data-target="#approveModal">Approve</button>
            {% endif %}
            {% endif %}
          </div>
        {% elif current_user.privelege==1 %}
          <div>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            {% if post.status==0%}
            <button type="button" class="btn btn-secondary btn-sm mt-1 mb-1" data-toggle="modal" data-target="#approveModal">Approve</button>
            {% endif %}
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal 1-->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Modal 2-->
  
  <div class="modal fade" id="approveModal" tabindex="-1" role="dialog" aria-labelledby="approveModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="approveModalLabel">Approve Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.approve_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Approve">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mySite/templates/under.html
<!DOCTYPE html>
<title>UNDER MAINTAINENCE</title>
<style>
  body { text-align: center; padding: 150px; }
  h1 { font-size: 50px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: left; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>

<article>
    <h1>We&rsquo;ll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need to you can always <a href="mailto:nkpparty@gmail.com">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
        <p>&mdash; The Team</p>
    </div>
</article>

mySite/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% if current_user.privelege==1 %}
      <div>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete User</button>
      </div>
    {% endif %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
    <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete User?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('users.delete_user', user_id=user.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}